# Generated by Django 3.0 on 2020-08-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('member', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSubjectTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT', null=True, verbose_name='최초등록 시각')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='MOD_DT', null=True, verbose_name='최종수정 시각')),
                ('use', models.IntegerField(db_column='USE', default=1, verbose_name='사용')),
                ('member_subject_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('auth_cd', models.CharField(blank=True, choices=[('VIEW', '골프'), ('WAIT', '필라테스'), ('DELETE', '웨이트 트레이닝')], db_column='AUTH_CD', default='', max_length=20, verbose_name='권한 코드')),
                ('own_cd', models.CharField(blank=True, choices=[('OWNER', '오너'), ('SHARE', '공유'), ('EMPLOYEE', '직원')], db_column='OWN_CD', default='OWNER', max_length=20, verbose_name='소유 코드')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.MemberTb', verbose_name='회원')),
                ('mod_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MOD_MEMBER_ID', to='member.MemberTb', verbose_name='최종수정 회원')),
                ('subject_tb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.SubjectTb', verbose_name='지점')),
            ],
            options={
                'verbose_name': '강사->수업 연결 정보',
                'verbose_name_plural': '강사->수업 연결 정보',
                'db_table': 'MEMBER_SUBJECT_TB',
                'managed': True,
            },
        ),
    ]
