# Generated by Django 3.0 on 2020-08-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberSubjectTb',
        ),
    ]
