# Generated by Django 3.0 on 2020-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionAuthTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT', null=True, verbose_name='최초등록 시각')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='MOD_DT', null=True, verbose_name='최종수정 시각')),
                ('use', models.IntegerField(db_column='USE', default=1, verbose_name='사용')),
                ('function_auth_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('function_auth_type_cd', models.CharField(blank=True, db_column='FUNCTION_AUTH_TYPE_CD', max_length=45, verbose_name='기능권한 타입')),
                ('function_auth_type_name', models.CharField(blank=True, db_column='FUNCTION_AUTH_TYPE_NAME', max_length=255, verbose_name='기능 권한명')),
                ('order', models.IntegerField(db_column='ORDER', default=1)),
            ],
            options={
                'verbose_name': '기능 권한',
                'verbose_name_plural': '기능 권한',
                'db_table': 'FUNCTION_AUTH_TB',
                'managed': False,
            },
        ),
    ]
