# Generated by Django 3.0 on 2020-08-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facilityauthtb_facilitytb_memberfacilitytb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitytb',
            old_name='subject_detail_nm',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='facilitytb',
            name='subject_cd',
        ),
    ]
