# Generated by Django 3.0 on 2020-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20200820_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytb',
            name='subject_tag',
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='contents',
            field=models.CharField(blank=True, db_column='CONTENTS', default='', max_length=3000, verbose_name='소개'),
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='main_img_url',
            field=models.URLField(blank=True, db_column='MAIN_IMG_URL', verbose_name='메인 이미지 URL'),
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='sub_img_url',
            field=models.URLField(blank=True, db_column='SUB_IMG_URL', verbose_name='서브 이미지 URL'),
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='support_tag',
            field=models.CharField(blank=True, db_column='SUPPORT_TAG', default='', max_length=3000, verbose_name='지원 태그'),
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='title',
            field=models.CharField(blank=True, db_column='TITLE', default='', max_length=1000, verbose_name='타이틀'),
        ),
    ]
