# Generated by Django 3.0 on 2020-08-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_auto_20200825_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytb',
            name='main_type_cd',
            field=models.CharField(blank=True, db_column='MAIN_TYPE_CD', default='', max_length=20, verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='facilitytb',
            name='sub_type_cd',
            field=models.CharField(blank=True, db_column='SUB_TYPE_CD', default='', max_length=20, verbose_name='소분류'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', default='', max_length=20, verbose_name='지점명'),
        ),
    ]
