# Generated by Django 3.0 on 2020-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_auto_20200825_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytb',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='main_img_url',
            field=models.URLField(blank=True, db_column='MAIN_IMG_URL', max_length=255, verbose_name='메인 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='main_type_cd',
            field=models.CharField(blank=True, choices=[('GOLF', '골프'), ('PI', '필라테스'), ('WT', '웨이트 트레이닝'), ('BL', '발레'), ('YG', '요가')], db_column='MAIN_TYPE_CD', default='', max_length=20, verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='start_date',
            field=models.DateField(blank=True, db_column='START_DATE', null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='sub_img_url',
            field=models.URLField(blank=True, db_column='SUB_IMG_URL', max_length=255, verbose_name='서브 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='facilitytb',
            name='sub_type_cd',
            field=models.CharField(blank=True, choices=[('INDOOR_FIELD', '실내 연습장'), ('OUTDOOR_FIELD', '실외 연습장'), ('SCREEN', '스크린 골프'), ('STUDIO', '전문 스튜디오')], db_column='SUB_TYPE_CD', default='', max_length=20, verbose_name='소분류'),
        ),
    ]
