UN_USE = 0
USE = 1

OWN_TYPE_OWNER = 'OWNER'
OWN_TYPE_SHARE = 'SHARE'
OWN_TYPE_EMPLOYEE = 'EMPLOYEE'

AUTH_TYPE_VIEW = 'VIEW'
AUTH_TYPE_WAIT = 'WAIT'
AUTH_TYPE_DELETE = 'DELETE'

LECTURE_TYPE_ONE_TO_ONE = 'ONE_TO_ONE'
LECTURE_TYPE_NORMAL = 'NORMAL'
