# Generated by Django 3.0 on 2020-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT', null=True, verbose_name='최초등록 시각')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='MOD_DT', null=True, verbose_name='최종수정 시각')),
                ('use', models.IntegerField(db_column='USE', default=1, verbose_name='사용')),
                ('member_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', default='', max_length=20, verbose_name='이름')),
                ('phone', models.CharField(blank=True, db_column='PHONE', default='', max_length=20, verbose_name='휴대폰')),
                ('sex', models.CharField(blank=True, db_column='SEX', default='', max_length=2, verbose_name='성별')),
                ('birthday_dt', models.DateField(blank=True, db_column='BIRTHDAY_DT', null=True, verbose_name='생년월일')),
                ('profile_url', models.CharField(blank=True, db_column='PROFILE_URL', default='/static/common/icon/icon_account.png', max_length=255, null=True, verbose_name='프로필 사진 URL')),
                ('phone_is_active', models.IntegerField(blank=True, db_column='PHONE_IS_ACTIVE', default=0, null=True, verbose_name='휴대폰 인증 여부')),
                ('reg_info', models.CharField(blank=True, db_column='REG_INFO', default='', max_length=20, verbose_name='생성자 회원 ID')),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True, verbose_name='나이')),
                ('country', models.CharField(blank=True, db_column='COUNTRY', default='', max_length=255, verbose_name='국가')),
                ('address', models.CharField(blank=True, db_column='ADDRESS', default='', max_length=255, verbose_name='지역')),
                ('job', models.CharField(blank=True, db_column='JOB', default='', max_length=20, verbose_name='직업')),
                ('contents', models.CharField(blank=True, db_column='CONTENTS', default='', max_length=255, verbose_name='소개')),
                ('recommended_member_id', models.CharField(blank=True, db_column='RECOMMENDED_MEMBER_ID', default='', max_length=20, verbose_name='추천 회원 ID')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'MEMBER_TB',
                'managed': False,
            },
        ),
    ]
